# Generated by Django 3.1.4 on 2020-12-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='topping_type',
        ),
        migrations.RenameField(
            model_name='toppingtype',
            old_name='type',
            new_name='topping_type',
        ),
    ]
