# Generated by Django 3.1.4 on 2020-12-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="topping",
        ),
        migrations.AddField(
            model_name="order",
            name="topping",
            field=models.ManyToManyField(to="pizza_app.Topping"),
        ),
    ]
