# Generated by Django 3.1.4 on 2020-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_auto_20201210_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingtype',
            name='topping_type',
        ),
        migrations.AddField(
            model_name='toppingtype',
            name='name',
            field=models.CharField(default='Basic Toppings*', max_length=100),
            preserve_default=False,
        ),
    ]
