# Generated by Django 3.1.4 on 2020-12-10 10:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza_app', '0003_auto_20201210_1011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('seller', 'size', 'price')},
        ),
    ]
